RSS_Reader/Models/Channel.cs
using System.Xml.Serialization;

namespace RSS_Reader.Models
{

    public class Channel
    {
        [XmlElement("title")]
        public string Title { get; init; } = null!;

        [XmlElement("link")]
        public string Link { get; init; } = null!;

        [XmlElement("description")]
        public string Description { get; init; } = null!;

        [XmlElement("language")]
        public string? Language { get; init; }

        [XmlElement("managingEditor ")]
        public string? ManagingEditor { get; init; }

        [XmlElement("pubDate")]
        public string? PubDate { get; init; }

        [XmlElement("image")]
        public Image Image { get; init; } = null!;

        [XmlElement("item")]
        public List<Item> Items { get; init; } = null!;
    }
}

RSS_Reader/Models/ErrorViewModel.cs
namespace RSS_Reader.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RSS_Reader/Models/FeedSettings.cs
namespace RSS_Reader.Models
{
    public class FeedSettings
    {
        public string Url { get; set; }
        public int SchedulerTime { get; set; }
    }
}

RSS_Reader/Models/Image.cs
using System.Xml.Serialization;

namespace RSS_Reader.Models
{
    public class Image
    {
        [XmlElement("link")]
        public string? Link { get; set; }

        [XmlElement("url")]
        public string Url { get; set; } = null!;

        [XmlElement("title")]
        public string? Title { get; set; }
    }
}

RSS_Reader/Models/Item.cs
using System.Xml.Serialization;

namespace RSS_Reader.Models
{
    public class Item
    {
        [XmlElement("title")]
        public string Title { get; set; } = null!;

        [XmlElement("link")]
        public string Link { get; set; } = null!;

        [XmlElement("description")]
        public string Description { get; set; } = null!;

        [XmlElement("pubDate")]
        public string? PubDate { get; set; }

        [XmlElement("category")]
        public List<string>? Category { get; set; }
    }
}

RSS_Reader/Models/Rss.cs
using System.Xml.Serialization;

namespace RSS_Reader.Models
{
    [XmlRoot("rss")]
    public class Rss
    {
        [XmlElement("channel")]
        public Channel Channel { get; init; } = null!;
    }
}

RSS_Reader/Controllers/RssController.cs
using Microsoft.AspNetCore.Mvc;
using RSS_Reader.Services;
using System.Text.Json;
using RSS_Reader.Models;

namespace RSS_Reader.Controllers
{
    public class RssController : Controller
    {
        IRssParserService _rssParser;
        IConfiguration _config;

        public RssController(IConfiguration config, IRssParserService rssParser)
        {
            _rssParser = rssParser;
            _config = config;
        }

        public async Task<ActionResult> Index()
        {
            Rss rss = null;
            if (Request.Cookies.Count == 0)
            {
                rss = await _rssParser.ParseRss(_config["feeds:feed:url"]);
                if (rss is not null)
                {
                    var feedSettings = new List<FeedSettings>
                    {
                        new FeedSettings { 
                            Url=_config["feeds:feed:url"], 
                            SchedulerTime=Convert.ToInt32(_config["feeds:feed:updateTimeMs"]) 
                        },
                    };

                    Response.Cookies.Append("feeds", JsonSerializer.Serialize(feedSettings)); 
                }
            }
            else
            {
                var feedSettings = JsonSerializer.Deserialize<List<FeedSettings>>(Request.Cookies["feeds"]);
                rss = await _rssParser.ParseRss(feedSettings[0].Url);
            }

            return View(rss);
        }

        [HttpGet]
        public async Task<ActionResult> UpdateFeed(string feed)
        {
            var rss = await _rssParser.ParseRss(feed);
            return PartialView("_Items", rss?.Channel?.Items);
        }
    }
}

RSS_Reader/Views/Rss/Index.cshtml
@{
    ViewData["Title"] = "RssReader";
}
@model Rss

<div class="row flex-xl-nowrap feeds">
    <section class="col-12 col-md-3 col-xl-2 bd-sidebar feeds-nav bg-secondary">
        <form class="addFeed mt-3" method="post" action="~/Rss/AddFeed">
            <input type="url" class="form-control mb-1" id="addFeddLink" placeholder="Link">
            <input type="number" class="form-control mb-1" id="addUpdateTimeMs" placeholder="Update time Ms">
            <button type="submit" class="btn btn-primary mb-1">Add</button>
        </form>
        <div id="feeds-titles" class="list-group mt-3">
            <a class="list-group-item list-group-item-action bg-secondary" href="#" style="border: none; color: #fff;">
                <div class="d-flex w-100 align-items-center">
                    @if (Model?.Channel?.Image is not null)
                    {
                        <img src="@Model.Channel.Image.Url" 
                            class="rounded-circle" style="width: 64px;" alt="Avatar"/>
                    }
                    <h4 class="mb-1">@Model?.Channel?.Title</h4>
                </div>
            </a>
        </div>
    </section>
    <section class="bd-content row col-9 mt-3 feed">
        @{await Html.RenderPartialAsync("_Items", Model?.Channel?.Items);}
    </section>
</div>

RSS_Reader/Views/Rss/_Items.cshtml
@model IEnumerable<Item>

<div data-bs-target="#feed-items" class="items-descriptions col-8" tabindex="0">
    @if (Model is not null)
    {
        @for (int i = 0; i < Model.Count(); i++)
        {
            var item = Model.ElementAt(i);
            <div id="item-@i" class="item border-bottom">
                <h4><a href="@item.Link" target="_blank" style="text-decoration: none;">@item.Title</a></h4>
                <p class="item-description">@Html.Raw(item.Description)</p>
            </div>
        }
    }
</div>
<div id="feed-items" class="list-group col-4" style="height: 80vh; overflow-y: scroll;">
    @if (Model is not null)
    {
        @for (int i = 0; i < Model.Count(); i++)
        {
            var item = Model.ElementAt(i);

            <a class="list-group-item list-group-item-action" href="#item-@i">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">@item.Title</h5>
                    <small>@DateTime.Parse(item.PubDate).ToString("dd.MM.yyyy")</small>
                </div>
            </a>
        }
    } 
</div>

RSS_Reader/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/RSS_Reader.styles.css" />
</head>
<body>
    <header>
        @if (IsSectionDefined("Header"))
        {
            @RenderSection("Header", false)
        }
        else
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Rss" asp-action="Index">RssReader</a>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        @if (IsSectionDefined("NavBar"))
                        {
                            @RenderSection("NavBar", false);
                        }
                    </div>
                </div>
            </nav>
        }  
    </header>
    <div class="container-fluid">
        @RenderBody()
    </div>

    <footer>
        @if (IsSectionDefined("Footer"))
        {
            @RenderSection("Footer", false)
        }
        else
        {
            <div class="border-top footer text-muted fixed-bottom pt-10 pb-3 d-flex justify-content-center">
                &copy; Powered by GovnoCode 
            </div>
        }
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>